### DISCUSSION TITLE
Section 4 Airdrop and Signatures  Error: the path script/target/input.json is not allowed to be accessed for write operations (Read and Write Permissions)

### DISCUSSION THREAD

**Discussion by farman1094** [Cyfrin/foundry-full-course-cu#2553] [Q&A] [answered]
I am facing this issue in Airdrop and Signatures Lesson. I am trying to generate the `input.json` with the script name `GenerateInput`. Here is the exact error 
```bash
Farma@farman MINGW64 ~/OneDrive/Desktop/solidity/MerkleProof (master)
$ forge script script/GenerateInput.s.sol:GenerateInput
[⠊] Compiling...
[⠒] Compiling 37 files with Solc 0.8.26
[⠘] Solc 0.8.26 finished in 1.51s
Compiler run successful!
Traces:
  [788091] → new GenerateInput@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    └─ ← [Return] 3521 bytes of code

  [362778] GenerateInput::run()
    ├─ [0] VM::toString(4) [staticcall]
    │   └─ ← [Return] "4"
    ├─ [0] VM::toString(25000000000000000000 [2.5e19]) [staticcall]
    │   └─ ← [Return] "25000000000000000000"
    ├─ [0] VM::toString(0) [staticcall]
    │   └─ ← [Return] "0"
    ├─ [0] VM::toString(1) [staticcall]
    │   └─ ← [Return] "1"
    ├─ [0] VM::toString(2) [staticcall]
    │   └─ ← [Return] "2"
    ├─ [0] VM::toString(3) [staticcall]
    │   └─ ← [Return] "3"
    ├─ [0] VM::projectRoot() [staticcall]
    │   └─ ← [Return] "C:/Users/Farma/OneDrive/Desktop/solidity/MerkleProof"
    ├─ [0] VM::writeFile("C:/Users/Farma/OneDrive/Desktop/solidity/MerkleProof./script/target/input.json", "{ \"types\": [\"address\", \"uint\"], \"count\":4,\"values\": {\"0\": { \"0\":\"0x264F7948c23da2233D3458F1B4e2554f0e56c9Ca\", \"1\":\"25000000000000000000\" },\"1\": { \"0\":\"0x3c684e9D377F966f6794Da8b62ef54B1A41c75D1\", \"1\":\"25000000000000000000\" },\"2\": { \"0\":\"0xCe424b67cD1e7dA659e00dEe1C088eC9F370113B\", \"1\":\"25000000000000000000\" },\"3\": { \"0\":\"0xf6dBa02C01AF48Cf926579F77C9f874Ca640D91D\", \"1\":\"25000000000000000000\" }} }")
    │   └─ ← [Revert] vm.writeFile: the path script/target/input.json is not allowed to be accessed for write operations
    └─ ← [Revert] vm.writeFile: the path script/target/input.json is not allowed to be accessed for write operations
```

So basically this error is regarding the permission, that this specific files do not have the permission to write. Even though I have given the permission. Here is my foundry.toml

```toml
    [profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@OpenZeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "murky/=lib/murky/",
]
fs_permission = [{ access = "read-write", path = "./" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```

I have tried skipping this part and just manually copied the input but in next video we have to write from `input.json` in order to make proofs in `output.json`. 
I have tried this steps:
```bash
forge clean
forge update
foundryup
```
I have also tried changing or providing the path manually
```toml
fs_permission = [{ access = "read-write", path = "/script/targe/input" }]
```

**Comment by farman1094** [comment, marked as answer]
Now it's working wtf!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@OpenZeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "murky/=lib/murky/",
]
fs_permissions = [{ access = "read-write", path = "./" }]
# fs_permission = [{ access = "read-write", path = "./targe" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```
