### DISCUSSION TITLE
Foundry Fundamentals Section 2: Foundry Fund Me

### DISCUSSION THREAD

**Discussion by TheJazzDev** [Cyfrin/foundry-full-course-cu#3213] [Q&A] [answered]
Please after installing the Foundry Devops LIbrary ussed in the Interactions.s.sol script. The library couldn't locate the `forge-std` library. The path are not reconciling and i don't know why. `foundry-devops/src/DevOpsTools.sol` and `foundry-devops/src/ZkSyncChainChecker` these two files used some files from the `forge-std` library and it couldn't resolve the import.

![image](https://github.com/user-attachments/assets/445fd900-2a16-4bdd-bbe9-854693e6c893)

After i ran my test, i got error in console but the test still passed
```~/Documents/Tutorials/Cyfrin_Updraft/foundry-fund-me | on master +3 !5 ?9  forge test --match-test testUserCanFundAndOwnerWithdraw                                                                                         ok 
[⠰] Compiling...
[⠒] Compiling 22 files with Solc 0.8.19
[⠘] Solc 0.8.19 finished in 9.14s
Compiler run successful with warnings:
Warning (2072): Unused local variable.
  --> lib/foundry-devops/src/DevOpsTools.sol:40:17:
   |
40 |                 uint256 timestamp = vm.parseJsonUint(json, ".timestamp");
   |                 ^^^^^^^^^^^^^^^^^


Ran 1 test for test/integration/IntegrationsTest.t.sol:InteractionsTest
[PASS] testUserCanFundAndOwnerWithdraw() (gas: 1214673)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 36.03ms (6.88ms CPU time)

Ran 1 test suite in 63.72ms (36.03ms CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

Here is my foundry.toml file

```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]
ffl = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```
