### DISCUSSION TITLE
Intro to fuzz testing - Error with tests

### DISCUSSION THREAD

**Discussion by tesla809** [Cyfrin/foundry-full-course-cu#3905] [General]
I have the following error with the `testPerformUpkeepUpdatesRaffleStateAndEmitsRequestId()` function:
```
[⠊] Compiling...
No files changed, compilation skipped

Ran 1 test for test/unit/RaffleTest.t.sol:RaffleTest
[FAIL: call didn't revert at a lower depth than cheatcode call depth; counterexample: calldata=0x9a3d2cf800000000000000000000000000000000ad6098fd8c3f669400a524f9bd205107 args=[230458006783599208740649291123416649991 [2.304e38]]] testFulfillRandomWordsCanOnlyBeCalledAfterPerformUpkeep(uint256) (runs: 0, μ: 0, ~: 0)
Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 6.66ms (2.31ms CPU time)

Ran 1 test suite in 147.29ms (6.66ms CPU time): 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/unit/RaffleTest.t.sol:RaffleTest
[FAIL: call didn't revert at a lower depth than cheatcode call depth; counterexample: calldata=0x9a3d2cf800000000000000000000000000000000ad6098fd8c3f669400a524f9bd205107 args=[230458006783599208740649291123416649991 [2.304e38]]] testFulfillRandomWordsCanOnlyBeCalledAfterPerformUpkeep(uint256) (runs: 0, μ: 0, ~: 0)
```

Here is the following code:
```solidity
    /* 
    * FullfillRandomWords
    */

    function testFulfillRandomWordsCanOnlyBeCalledAfterPerformUpkeep(uint256 randomRequestId) public raffleEntered skipFork {
        // Arrange
        // Act / Assert
        vm.expectRevert(VRFCoordinatorV2_5Mock.InvalidRequest.selector);
        // vm.mockCall could be used here...
        VRFCoordinatorV2_5Mock(vrfCoordinatorV2_5).fulfillRandomWords(0, address(raffle));

        vm.expectRevert(VRFCoordinatorV2_5Mock.InvalidRequest.selector);
        VRFCoordinatorV2_5Mock(vrfCoordinatorV2_5).fulfillRandomWords(1, address(raffle));

        vm.expectRevert(VRFCoordinatorV2_5Mock.InvalidRequest.selector);
        VRFCoordinatorV2_5Mock(vrfCoordinatorV2_5).fulfillRandomWords(randomRequestId, address(raffle));
    
    }
```

Along with the `foundry.toml` file:
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@chainlink/contracts/=lib/chainlink/contracts/",
  "@solmate=lib/solmate/src/",
]
fs_permissions = [
  { access="read", path = "./broadcast" },
  { access="read", path = "./reports" }
]
[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

```
